### ISSUE TITLE
Space and other parameters encoding in GET method

### ISSUE THREAD

**Issue by namsor** [namsor/namsor-r-sdk2#1]
The parameters are not properly encoded in the GET method,

`
    var.first.name <- 'John H.' # character |
    var.last.name <- 'Smith' # character |

    #Infer the likely gender of a name.
    api.instance <- PersonalApi$new()
    # Configure API key authorization: api_key
    api.instance$apiClient$apiKeys['X-API-KEY'] <- 'my api key';
    result <- api.instance$Gender(var.first.name, var.last.name)
    print(result)`

doesn't work because of the space in 'John H.'. This is because the GET method requires encoding special characters in the API URL.

Workaround : use the batch POST methods instead.

**Comment by wing328** [comment]
I've pushed a fix (https://github.com/namsor/namsor-r-sdk2/commit/88eeaecc3e3efaa784fe3737619c8ece3df53b24) and added a test case to cover the issue moving forward.

**Comment by wing328** [comment]
And the CI tests passed: https://travis-ci.com/namsor/namsor-r-sdk2/builds/104365651
