### ISSUE TITLE
"Error: object 'PersonalApi' not found"

### ISSUE THREAD

**Issue by namsor** [namsor/namsor-r-sdk2#6]
I am trying to use the namsor package in R. I installed the package and tried to run a test example, but got an error at the following line:

api.instance <- PersonalApi$new()

The error being "Error: object 'PersonalApi' not found". I installed the package in R using:

install.packages("remotes")
remotes::install_github("namsor/namsor-r-sdk2")

**Comment by wing328** [comment]
Fixed via https://github.com/namsor/namsor-r-sdk2/pull/5
